"use client"
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { PHProvider } from "@/app/posthog-provider";
import dynamic from "next/dynamic";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

const PostHogPageView = dynamic(() => import('@/lib/posthog-pageview'), {
  ssr: false,
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
          >
          <PHProvider>
            <PostHogPageView />
            {children}
          </PHProvider>
        </body>
    </html>
  );
}
